version: '3'
services:
  # Rails
  web:
    build: .

    # sh → shell でrailsサーバーが開いていたら、killして、起動
    # p 3000　portnumber
    # [rails s -> pumactl start]
    # bundle exec -> rails
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # 編集した内容が、自動でrailsサーバーに直接反映させる
    #（pc上のカレントディレクトリから、コンテナ上の「/app」にマウント
    volumes:
      - .:/app
    ports:
      - 3000:3000

    # dbのコンテナが立ち上がってから、webへ
    depends_on:
      - db

# Mysql
  db:
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:

